//
//  SubscriptionFreeTrialStore.swift
//  DemoFlow
//
//  Persists the one-time promotional trial in the local Keychain. The ID is
//  generated by DemoFlow and is not derived from device hardware.
//

import Foundation
import Security

struct SubscriptionFreeTrialStore {
    static let shared = SubscriptionFreeTrialStore()
    static let trialDays = 7

    private struct Claim: Codable {
        let deviceID: String
        let claimedAt: Date
        let expiresAt: Date
    }

    private enum ReadResult {
        case missing
        case data(Data)
        case unavailable
    }

    private let service: String
    private let deviceIDAccount = "free-trial-device-id-v1"
    private let claimAccount = "free-trial-claim-v1"
    private let lock = NSLock()

    init(bundleIdentifier: String? = Bundle.main.bundleIdentifier) {
        service = "\(bundleIdentifier ?? "demoflow").subscription"
    }

    var canClaimTrial: Bool {
        lock.lock()
        defer { lock.unlock() }

        guard case .missing = read(account: claimAccount) else { return false }
        return loadOrCreateDeviceID() != nil
    }

    func activeTrialExpirationDate(now: Date = Date()) -> Date? {
        lock.lock()
        defer { lock.unlock() }

        guard case let .data(data) = read(account: claimAccount),
              let claim = try? JSONDecoder().decode(Claim.self, from: data),
              claim.expiresAt > now else {
            return nil
        }
        return claim.expiresAt
    }

    func hasClaimedTrial() -> Bool {
        lock.lock()
        defer { lock.unlock() }
        if case .data = read(account: claimAccount) {
            return true
        }
        return false
    }

#if DEBUG
    /// This is intentionally unavailable to TestFlight and App Store builds.
    /// It lets Xcode developers start a fresh local subscription test cycle.
    func resetForDebugTesting() {
        lock.lock()
        defer { lock.unlock() }

        delete(account: claimAccount)
        delete(account: deviceIDAccount)
    }
#endif

    @discardableResult
    func claim(now: Date = Date()) -> Date? {
        lock.lock()
        defer { lock.unlock() }

        guard case .missing = read(account: claimAccount),
              let deviceID = loadOrCreateDeviceID(),
              let expiresAt = Calendar.current.date(byAdding: .day, value: Self.trialDays, to: now),
              let data = try? JSONEncoder().encode(
                  Claim(deviceID: deviceID, claimedAt: now, expiresAt: expiresAt)
              ),
              add(data: data, account: claimAccount) else {
            return nil
        }
        return expiresAt
    }

    private func loadOrCreateDeviceID() -> String? {
        if case let .data(data) = read(account: deviceIDAccount),
           let value = String(data: data, encoding: .utf8),
           !value.isEmpty {
            return value
        }

        let newValue = UUID().uuidString
        guard add(data: Data(newValue.utf8), account: deviceIDAccount) else {
            if case let .data(data) = read(account: deviceIDAccount),
               let existingValue = String(data: data, encoding: .utf8),
               !existingValue.isEmpty {
                return existingValue
            }
            return nil
        }
        return newValue
    }

    private func query(account: String, returningData: Bool = false) -> [String: Any] {
        var value: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecAttrSynchronizable as String: false
        ]
        if returningData {
            value[kSecReturnData as String] = true
            value[kSecMatchLimit as String] = kSecMatchLimitOne
        }
        return value
    }

    private func read(account: String) -> ReadResult {
        var result: CFTypeRef?
        let status = SecItemCopyMatching(
            query(account: account, returningData: true) as CFDictionary,
            &result
        )
        switch status {
        case errSecSuccess:
            return (result as? Data).map(ReadResult.data) ?? .unavailable
        case errSecItemNotFound:
            return .missing
        default:
            return .unavailable
        }
    }

    private func add(data: Data, account: String) -> Bool {
        var value = query(account: account)
        value[kSecValueData as String] = data
        value[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlock
        return SecItemAdd(value as CFDictionary, nil) == errSecSuccess
    }

    private func delete(account: String) {
        let status = SecItemDelete(query(account: account) as CFDictionary)
        guard status == errSecSuccess || status == errSecItemNotFound else { return }
    }
}
